### ISSUE TITLE
build error with the last version 3.4.2

### ISSUE THREAD

**Issue by kamilml** [nanxiaobei/antd-img-crop#48] opened 2020-06-11 09:33 UTC
I am sorry, I have another problem :(

With crop 3.3.0 my build was fine, but with the new version 3.4.2 I got this error
![](https://i.imgur.com/r2TZDvy.png)

I try many many times install and unistall different version of another packages like nextjs or antd (because I thought is a problem of the new versions of nextjs or antd, but the problem just occurs when I update `antd-img-crop` to `3.4.2`

This is my stable dependencies version. If I update crop the build crashes :(
```json
"dependencies": {
        "@next/bundle-analyzer": "^9.4.4",
        "@reduxjs/toolkit": "^1.3.6",
        "@zeit/next-less": "^1.0.1",
        "antd": "^4.3.3",
        "antd-img-crop": "^3.3.0",
        "isomorphic-unfetch": "^3.0.0",
        "next": "^9.4.4",
        "next-antd-aza-less": "^1.0.2",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "react-redux": "^7.2.0"
    }
```

**Comment by nanxiaobei** [comment] 2020-06-12 15:45
Duplicate of #47

**Closed by nanxiaobei** 2020-06-12 15:45 UTC
